name: getir-api-deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEYFILE }}

      - name: Build docker image and push it to Google Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/getir-api

      - name: Deploy image to cloud run
        run: |-
          gcloud run deploy getir-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/getir-api \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --set-env-vars "MONGODB_URL=${{ secrets.MONGODB_URL }}"
